import { getLocale } from "@opencode-ai/tui/i18n"

const zh = {
  "show help": "显示帮助",
  "show version number": "显示版本号",
  "print logs to stderr": "将日志输出到 stderr",
  "log level": "日志级别",
  "run without external plugins": "不加载外部插件运行",
  "generate shell completion script": "生成 Shell 补全脚本",
  "port to listen on": "监听端口",
  "hostname to listen on": "监听主机名",
  "enable mDNS service discovery (defaults hostname to 0.0.0.0)": "启用 mDNS 服务发现（默认主机名为 0.0.0.0）",
  "custom domain name for mDNS service (default: hypercode.local)": "mDNS 服务的自定义域名（默认：hypercode.local）",
  "additional domains to allow for CORS": "允许 CORS 的其他域名",
  "start ACP (Agent Client Protocol) server": "启动 ACP（智能体客户端协议）服务器",
  "working directory": "工作目录",
  "attach to a running HyperCode server": "连接到正在运行的 HyperCode 服务器",
  "http://localhost:4096": "http://localhost:4096",
  "directory to run in": "运行目录",
  "continue the last session": "继续上一个会话",
  "session id to continue": "要继续的会话 ID",
  "fork the session when continuing (use with --continue or --session)": "继续时分叉会话（与 --continue 或 --session 配合使用）",
  "basic auth password (defaults to OPENCODE_SERVER_PASSWORD)": "Basic Auth 密码（默认读取 OPENCODE_SERVER_PASSWORD）",
  "basic auth username (defaults to OPENCODE_SERVER_USERNAME or 'opencode')": "Basic Auth 用户名（默认读取 OPENCODE_SERVER_USERNAME，或使用 'opencode'）",
  "start the minimal interactive interface": "启动精简交互界面",
  "disable mini session history replay on resume and after resize": "恢复会话或调整窗口大小后不重放精简界面历史",
  "cap visible mini replay to the newest N messages": "精简界面最多显示最近 N 条重放消息",
  "create a new agent": "创建新智能体",
  "directory path to generate the agent file": "生成智能体文件的目录路径",
  "what the agent should do": "智能体的职责说明",
  "agent mode": "智能体模式",
  "model to use in the format of provider/model": "要使用的模型，格式为 provider/model",
  "list all available agents": "列出所有可用智能体",
  "manage agents": "管理智能体",
  "open an interactive sqlite3 shell or run a query": "打开交互式 sqlite3 Shell 或执行查询",
  "SQL query to execute": "要执行的 SQL 查询",
  "Output format": "输出格式",
  "output format": "输出格式",
  "print the database path": "输出数据库路径",
  "database tools": "数据库工具",
  "export session data as JSON": "将会话数据导出为 JSON",
  "session id to export": "要导出的会话 ID",
  "redact sensitive transcript and file data": "脱敏会话记录和文件中的敏感数据",
  "import session data from JSON file or URL": "从 JSON 文件或 URL 导入会话数据",
  "path to JSON file or share URL": "JSON 文件路径或分享 URL",
  "install the GitHub agent": "安装 GitHub 智能体",
  "run the GitHub agent": "运行 GitHub 智能体",
  "GitHub mock event to run the agent for": "供智能体运行的 GitHub 模拟事件",
  "GitHub personal access token (github_pat_********)": "GitHub 个人访问令牌（github_pat_********）",
  "manage GitHub agent": "管理 GitHub 智能体",
  "license tools": "许可证工具",
  "print this machine's license ID": "输出此设备的许可证 ID",
  "print the license file path": "输出许可证文件路径",
  "check the current license status": "检查当前许可证状态",
  "manage MCP (Model Context Protocol) servers": "管理 MCP（模型上下文协议）服务器",
  "list MCP servers and their status": "列出 MCP 服务器及其状态",
  "authenticate with an OAuth-enabled MCP server": "认证支持 OAuth 的 MCP 服务器",
  "name of the MCP server": "MCP 服务器名称",
  "list OAuth-capable MCP servers and their auth status": "列出支持 OAuth 的 MCP 服务器及认证状态",
  "remove OAuth credentials for an MCP server": "移除 MCP 服务器的 OAuth 凭据",
  "add an MCP server": "添加 MCP 服务器",
  "URL for a remote MCP server": "远程 MCP 服务器 URL",
  "environment variable for a local MCP server (KEY=VALUE)": "本地 MCP 服务器环境变量（KEY=VALUE）",
  "HTTP header for a remote MCP server (KEY=VALUE)": "远程 MCP 服务器 HTTP 请求头（KEY=VALUE）",
  "debug OAuth connection for an MCP server": "调试 MCP 服务器的 OAuth 连接",
  "list all available models": "列出所有可用模型",
  "provider ID to filter models by": "按提供商 ID 筛选模型",
  "use more verbose model output (includes metadata like costs)": "显示更详细的模型信息（包括费用等元数据）",
  "refresh the models cache from models.dev": "从 models.dev 刷新模型缓存",
  "install plugin and update config": "安装插件并更新配置",
  "npm module name": "npm 模块名称",
  "install in global config": "安装到全局配置",
  "replace existing plugin version": "替换现有插件版本",
  "PR number to checkout": "要检出的 PR 编号",
  "manage AI providers and credentials": "管理 AI 提供商和凭据",
  "list providers and credentials": "列出提供商和凭据",
  "log in to a provider": "登录提供商",
  "hypercode auth provider": "hypercode auth provider",
  "provider id or name to log in to (skips provider selection)": "要登录的提供商 ID 或名称（跳过提供商选择）",
  "login method label (skips method selection)": "登录方式标签（跳过方式选择）",
  "log out from a configured provider": "退出已配置的提供商",
  "provider id or name to log out from": "要退出的提供商 ID 或名称",
  "run HyperCode with a message": "使用消息运行 HyperCode",
  "message to send": "要发送的消息",
  "the command to run, use message for args": "要运行的命令，参数使用 message",
  "fork the session before continuing (requires --continue or --session)": "继续前分叉会话（需要 --continue 或 --session）",
  "share the session": "分享会话",
  "agent to use": "要使用的智能体",
  "format: default (formatted) or json (raw JSON events)": "格式：default（格式化输出）或 json（原始 JSON 事件）",
  "file(s) to attach to message": "附加到消息的文件",
  "title for the session (uses truncated prompt if no value provided)": "会话标题（未提供时使用截断后的输入）",
  "attach to a running HyperCode server (e.g., http://localhost:4096)": "连接到正在运行的 HyperCode 服务器（例如 http://localhost:4096）",
  "directory to run in, path on remote server if attaching": "运行目录；连接远程服务器时为远程路径",
  "port for the local server (defaults to random port if no value provided)": "本地服务器端口（未提供时随机选择）",
  "model variant (provider-specific reasoning effort, e.g., high, max, minimal)": "模型变体（提供商特定的推理强度，例如 high、max、minimal）",
  "show thinking blocks": "显示思考区块",
  "replay interactive session history on resume and after resize (use --no-replay to disable)": "恢复会话或调整窗口大小后重放交互历史（使用 --no-replay 禁用）",
  "cap visible interactive replay to the newest N messages": "交互界面最多显示最近 N 条重放消息",
  "run in direct interactive split-footer mode": "以直接交互的分栏底部模式运行",
  "auto-approve permissions that are not explicitly denied (dangerous!)": "自动批准未明确拒绝的权限（危险！）",
  "enable direct interactive demo slash commands; pass one as the message to run it immediately": "启用直接交互演示斜杠命令；将命令作为消息可立即运行",
  "start a headless HyperCode server": "启动无界面的 HyperCode 服务器",
  "manage sessions": "管理会话",
  "delete a session": "删除会话",
  "session ID to delete": "要删除的会话 ID",
  "list sessions": "列出会话",
  "limit to N most recent sessions": "仅显示最近 N 个会话",
  "show token usage and cost statistics": "显示 Token 用量和费用统计",
  "show stats for the last N days (default: all time)": "显示最近 N 天的统计（默认：全部时间）",
  "number of tools to show (default: all)": "要显示的工具数量（默认：全部）",
  "show model statistics (default: hidden). Pass a number to show top N, otherwise shows all": "显示模型统计（默认隐藏）；传入数字显示前 N 项，否则显示全部",
  "filter by project (default: all projects, empty string: current project)": "按项目筛选（默认：全部项目；空字符串：当前项目）",
  "start the HyperCode TUI": "启动 HyperCode TUI",
  "path to start HyperCode in": "HyperCode 启动路径",
  "prompt to use": "要使用的输入",
  "uninstall HyperCode and remove all related files": "卸载 HyperCode 并移除所有相关文件",
  "keep configuration files": "保留配置文件",
  "keep session data and snapshots": "保留会话数据和快照",
  "show what would be removed without removing": "仅显示将移除的内容，不实际删除",
  "skip confirmation prompts": "跳过确认提示",
  "upgrade HyperCode to the latest or a specific version": "将 HyperCode 升级到最新版本或指定版本",
  "version to upgrade to, for ex '0.1.48' or 'v0.1.48'": "要升级到的版本，例如 '0.1.48' 或 'v0.1.48'",
  "installation method to use": "要使用的安装方式",
  "start HyperCode server and open the web interface": "启动 HyperCode 服务器并打开 Web 界面",
  "fetch and checkout a GitHub PR branch, then run HyperCode": "获取并检出 GitHub PR 分支，然后运行 HyperCode",
  "log in to console": "登录控制台",
  "log out from console": "退出控制台",
  "account email to log out from": "要退出的账户邮箱",
  "switch active org": "切换当前组织",
  "list orgs": "列出组织",
  "open active console account": "打开当前控制台账户",
  "server URL": "服务器 URL",
  "debugging and troubleshooting tools": "调试和故障排查工具",
  "show agent configuration details": "显示智能体配置详情",
  "show resolved configuration": "显示解析后的配置",
  "file system debugging utilities": "文件系统调试工具",
  "LSP debugging utilities": "LSP 调试工具",
  "ripgrep debugging utilities": "ripgrep 调试工具",
  "snapshot debugging utilities": "快照调试工具",
  "print startup timing": "输出启动耗时",
  "debug v2 catalog and built-in plugins": "调试 v2 目录和内置插件",
  "show global paths (data, config, cache, state)": "显示全局路径（data、config、cache、state）",
  "list all known projects": "列出所有已知项目",
  "list all available skills": "列出所有可用技能",
  "wait indefinitely (for debugging)": "无限等待（用于调试）",
  "show debug information": "显示调试信息",
  "track current snapshot state": "跟踪当前快照状态",
  "show diff for a snapshot hash": "显示指定快照哈希的差异",
  "show patch for a snapshot hash": "显示指定快照哈希的补丁",
  "hash": "哈希",
  "list files using ripgrep": "使用 ripgrep 列出文件",
  "search file contents using ripgrep": "使用 ripgrep 搜索文件内容",
  "search files by query": "按查询搜索文件",
  "get diagnostics for a file": "获取文件诊断信息",
  "get symbols from a document": "获取文档符号",
  "search workspace symbols": "搜索工作区符号",
  "Search query": "搜索查询",
  "read file contents as JSON": "以 JSON 格式读取文件内容",
  "File path to read": "要读取的文件路径",
  "list files in a directory": "列出目录中的文件",
  "File path to list": "要列出的文件路径",
  "Agent name": "智能体名称",
  "Tool id to execute": "要执行的工具 ID",
  "Tool params as JSON or a JS object literal": "工具参数（JSON 或 JavaScript 对象字面量）",
  "Filter files by query": "按查询筛选文件",
  "Glob pattern to match files": "匹配文件的 Glob 模式",
  "Limit number of results": "限制结果数量",
  "Search pattern": "搜索模式",
  "File glob patterns": "文件 Glob 模式",
} as const

export function cliText(value: string) {
  if (getLocale() === "en") return value
  if (value.startsWith("comma-separated list of permissions to allow")) {
    return value.replace(
      /^comma-separated list of permissions to allow \(default: all\)\. Available:/,
      '允许的权限列表（逗号分隔，默认：全部）。可用权限：',
    )
  }
  return zh[value as keyof typeof zh] ?? value
}
